name: moxplatform_android
description: Android implementation of moxplatform
version: 0.1.7
homepage: https://codeberg.org/moxxy/moxplatform
publish_to: https://git.polynom.me/api/packages/Moxxy/pub

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    implements: moxplatform
    platforms:
      android:
        package: me.polynom.moxplatform_android
        pluginClass: MoxplatformAndroidPlugin
        dartPluginClass: MoxplatformAndroidPlugin

dependencies:
  flutter:
    sdk: flutter
  moxplatform_platform_interface:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: 0.1.7
  moxplatform:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: 0.1.7

  moxlib:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: 0.1.4
  logging: 1.0.2
  get_it: 7.2.0
  uuid: 3.0.5
  media_scanner: 2.0.0
  plugin_platform_interface: 2.1.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
