name: moxplatform_linux
description: Linux-specific implementation of moxplatform
version: 0.1.5
homepage: https://codeberg.org/moxxy/moxplatform

environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  moxplatform:
    path: ../moxplatform
   #hosted: https://git.polynom.me/api/packages/Moxxy/pub
   #version: 0.1.4
  moxplatform_generic:
    path: ../moxplatform_generic

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: moxplatform
    platforms:
      linux:
        dartPluginClass: MoxplatformLinuxPlugin
        
