name: moxplatform_platform_interface
description: A common platform interface for the my_plugin plugin.
version: 0.1.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.0
  moxplatform:
    git:
      url: https://codeberg.org/moxxy/moxplatform.git
      rev: c3f7091e00d6ecea85c6b62061e94d63c623ec04
      path: src/moxplatform
   #path: ../moxplatform

  moxlib:
    git:
      url: https://codeberg.org/moxxy/moxlib.git
      rev: 020c592d459654b7a807f115bd70809b3cf522bd

dev_dependencies:
  flutter_test:
    sdk: flutter
