name: moxplatform_platform_interface
description: A common platform interface for the my_plugin plugin.
version: 0.1.5
homepage: https://codeberg.org/moxxy/moxplatform
publish_to: https://pub.polynom.me

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  moxplatform:
   #path: ../moxplatform
    hosted: https://pub.polynom.me
    version: 0.1.5

  moxlib:
    hosted: https://pub.polynom.me
    version: 0.1.3
  plugin_platform_interface: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
