name: moxplatform_android
description: Android implementation of moxplatform
version: 0.1.18
homepage: https://codeberg.org/moxxy/moxplatform
publish_to: https://git.polynom.me/api/packages/Moxxy/pub

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    implements: moxplatform
    platforms:
      android:
        package: me.polynom.moxplatform_android
        pluginClass: MoxplatformAndroidPlugin
        dartPluginClass: MoxplatformAndroidPlugin

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  logging: ^1.0.2
  meta: ^1.7.0
  moxlib:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: ^0.2.0

  moxplatform:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: ^0.1.17+2
  moxplatform_platform_interface:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: ^0.1.18

  plugin_platform_interface: ^2.1.2
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: 10.1.4
  very_good_analysis: ^3.0.1
