name: moxplatform_generic
description: Generic implementations of moxplatform
version: 0.1.10
homepage: https://git.polynom.me/api/packages/Moxxy/pub

environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  moxplatform:
    path: ../moxplatform
   #hosted: https://git.polynom.me/api/packages/Moxxy/pub
   #version: 0.1.10
  moxplatform_platform_interface:
    path: ../moxplatform_platform_interface
   #hosted: https://git.polynom.me/api/packages/Moxxy/pub
   #version: 0.1.10

  moxlib:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: 0.1.3
    
  logging: 1.0.2
  get_it: 7.2.0
  uuid: 3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
