name: moxplatform
description: Moxxy platform-specific code
version: 0.1.11+1
publish_to: https://git.polynom.me/api/packages/Moxxy/pub

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: moxplatform_android
      linux:
        default_package: moxplatform_linux

dependencies:
  flutter:
    sdk: flutter

  moxlib:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: ^0.1.4
    
  moxplatform_android:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: ^0.1.11+1
  moxplatform_platform_interface:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: ^0.1.11+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.2
  very_good_analysis: ^2.4.0
