name: moxplatform
description: Moxxy platform-specific code
version: 0.1.6
publish_to: https://pub.polynom.me

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: moxplatform_android
      linux:
        default_package: moxplatform_linux

dependencies:
  flutter:
    sdk: flutter

  moxplatform_android:
    hosted: https://pub.polynom.me
    version: 0.1.6
   #path: ../moxplatform_android
  moxplatform_platform_interface:
   #path: ../moxplatform_platform_interface
    hosted: https://pub.polynom.me
    version: 0.1.6

  moxlib:
    hosted: https://pub.polynom.me
    version: 0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: 2.0.0
